# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Android APK

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [develop]
    paths:
      - '.github/workflows/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'lib/**'
      - 'ios/**'
      - 'android/**'

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Clone Flutter Source Code
      run: git clone --depth 1 https://github.com/flutter/flutter.git
      
    - name: Set up Flutter
      run: |
        cd flutter
        flutter_branch=$(git rev-parse --abbrev-ref HEAD)
        flutter_version=$(git describe --tags --abbrev=0)
        echo "::set-output name=flutter_branch::$flutter_branch"
        echo "::set-output name=flutter_version::$flutter_version"
        flutter/bin/flutter doctor -v

    - name: Build Flutter
      run: |
        cd flutter
        flutter/bin/flutter build apk --release

    - name: Build Flutter Project
      run: flutter/bin/flutter build apk --release
