name: Build Desktop APK

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    branches: [develop]
    paths:
      - '.github/workflows/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'
      - 'lib/**'
      - 'ios/**'
      - 'android/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.19.0
    - run: flutter --version

    - name: Get dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows

    - name: Upload Windows App
      uses: actions/upload-artifact@v4
      with:
        name: desktop-app-release
        path: build/app/outputs/flutter-apk/desktop-release.exe
